main: xyz.acrylicstyle.storageBox.StorageBoxPlugin
name: StorageBox
version: 0.0.4-SNAPSHOT
api-version: 1.15
author: acrylic-style

depend:
  - mcMMO

commands:
  storagebox:
    aliases: ["sb", "storage"]
